In [1]:
import requests
import json
import pandas as pd
import io
token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVkZW50aWFscyI6InByaXZhdGUtZGF0YS1wbGF0Zm9ybS1rZXkgZm9yIGFscGhhIiwiY3JlYXRlZEF0IjoiMjAyMS0wNi0yOFQxODoxNjoyOC4yNThaIiwiaWF0IjoxNjI0OTA0MTg4fQ.ITcG3EO90Uzc9JZYjE6g5mbmh4kkHBDO6QEumQ8ZruQ'

In [2]:
url1="https://endapi.truefeedback.io/dataplatform/survey/78"
s=requests.get(url1,headers={"auth": token}).content

In [3]:
data = json.loads(s.decode('utf-8'))

In [4]:
data

{'id': '78',
 'title': {'tr': 'Konya Elektronik Market Anketi'},
 'description': {'tr': 'Konya Elektronik Market Anketi'},
 'totalTfb': 50000,
 'image': 'randCollection/back_24.png',
 'startDate': '2021-06-23T08:55:04.207Z',
 'endDate': None,
 'participantLimit': '1000',
 'questions': [{'data': [{'label': 'Vatan'},
    {'label': 'Media Markt'},
    {'label': 'Teknosa'},
    {'label': 'Diğer'}],
   'multiple': 1,
   'question': 'Konya Kentplaza AVM’de hangi elektronik mağazasını görmek istersiniz?',
   'component': 'RadioGroup'},
  {'multiple': 1,
   'question': 'Önceki soruyu "diğer" olarak cevaplamışsanız lütfen ne olduğunu giriniz.',
   'component': 'TextInput'},
  {'data': [{'label': 'Vatan'},
    {'label': 'Media Markt'},
    {'label': 'Teknosa'},
    {'label': 'İnternet Pazar Yerleri'},
    {'label': 'Diğer'}],
   'multiple': 1,
   'question': 'En son hangi elektronik mağazasından alışveriş yaptınız?',
   'component': 'RadioGroup'},
  {'multiple': 1,
   'question': 'Önceki soruyu "diğer" olarak cevaplamışsanız lütfen ne olduğunu giriniz.',
   'component': 'TextInput'},
  {'data': [{'label': 'Ürünü görmek'},
    {'label': 'Satış temsilcisinden hızlı bilgiye erişebilmek'},
    {'label': 'Alışkanlık'},
    {'label': 'Satın alma davranışı sonrasında muhatap kişiye kolay ulaşım'},
    {'label': 'Güvenilir olması'},
    {'label': 'Aktüel'},
    {'label': 'Diğer'}],
   'multiple': 1,
   'question': 'İnternet alışverişi yerine mağazadan alışveriş yapma sebebiniz nedir?',
   'component': 'RadioGroup'},
  {'multiple': 1,
   'question': 'Önceki soruyu "diğer" olarak cevaplamışsanız lütfen ne olduğunu giriniz.',
   'component': 'TextInput'},
  {'data': [{'label': 'Kentplaza AVM'},
    {'label': 'Kule Site'},
    {'label': 'M1'},
    {'label': 'Novaland'},
    {'label': 'Selçuker Center'},
    {'label': 'Diğer'}],
   'multiple': 1,
   'question': 'Konya ilinde elektronik ürün alışverişi için hangi AVM’yi tercih edersiniz?',
   'component': 'RadioGroup'},
  {'multiple': 1,
   'question': 'Önceki soruyu "diğer" olarak cevaplamışsanız lütfen ne olduğunu giriniz.',
   'component': 'TextInput'},
  {'data': [{'label': 'Kentplaza AVM'},
    {'label': 'Kule Site'},
    {'label': 'M1'},
    {'label': 'Novaland'},
    {'label': 'Selçuker Center'},
    {'label': 'Diğer'}],
   'multiple': 1,
   'question': 'En son hangi AVM’den elektronik ürün satın aldınız?',
   'component': 'RadioGroup'},
  {'multiple': 1,
   'question': 'Önceki soruyu "diğer" olarak cevaplamışsanız lütfen ne olduğunu giriniz.',
   'component': 'TextInput'}]}

In [5]:
p= pd.DataFrame.from_dict(data['questions'])

p.head(10)

,data,multiple,question,component
0,"[{'label': 'Vatan'}, {'label': 'Media Markt'},...",1,Konya Kentplaza AVM’de hangi elektronik mağaza...,RadioGroup
1,NaN,1,"Önceki soruyu ""diğer"" olarak cevaplamışsanız l...",TextInput
2,"[{'label': 'Vatan'}, {'label': 'Media Markt'},...",1,En son hangi elektronik mağazasından alışveriş...,RadioGroup
3,NaN,1,"Önceki soruyu ""diğer"" olarak cevaplamışsanız l...",TextInput
4,"[{'label': 'Ürünü görmek'}, {'label': 'Satış t...",1,İnternet alışverişi yerine mağazadan alışveriş...,RadioGroup
5,NaN,1,"Önceki soruyu ""diğer"" olarak cevaplamışsanız l...",TextInput
6,"[{'label': 'Kentplaza AVM'}, {'label': 'Kule S...",1,Konya ilinde elektronik ürün alışverişi için h...,RadioGroup
7,NaN,1,"Önceki soruyu ""diğer"" olarak cevaplamışsanız l...",TextInput
8,"[{'label': 'Kentplaza AVM'}, {'label': 'Kule S...",1,En son hangi AVM’den elektronik ürün satın ald...,RadioGroup
9,NaN,1,"Önceki soruyu ""diğer"" olarak cevaplamışsanız l...",TextInput

In [6]:
p['question'][1]

'Önceki soruyu "diğer" olarak cevaplamışsanız lütfen ne olduğunu giriniz.'

In [7]:
url='https://endapi.truefeedback.io/dataplatform/survey/78/answers?limit=1500&offset=0'
s=requests.get(url,headers={"auth": token}).content
k=pd.read_json(s)
k

,_docType,answers,createdAt,id,uid
0,survey,"{'0': {'selected': [2], 'values': []}, '1': {'...",2021-07-10T15:53:44.791Z,78,160147
1,survey,"{'0': {'selected': [1], 'values': []}, '1': {'...",2021-07-10T15:31:13.455Z,78,155852
2,survey,"{'0': {'selected': [0], 'values': []}, '1': {'...",2021-07-10T15:25:38.687Z,78,155874
3,survey,"{'0': {'selected': [1], 'values': []}, '1': {'...",2021-07-10T15:14:45.167Z,78,160696
4,survey,"{'0': {'selected': [0], 'values': []}, '1': {'...",2021-07-10T14:34:03.033Z,78,152246
...,...,...,...,...,...
647,survey,"{'0': {'selected': [2], 'values': []}, '1': {'...",2021-06-23T09:02:37.989Z,78,92541
648,survey,"{'0': {'selected': [1], 'values': []}, '1': {'...",2021-06-23T09:01:54.720Z,78,65692
649,survey,"{'0': {'selected': [2], 'values': []}, '1': {'...",2021-06-23T09:00:03.521Z,78,65699
650,survey,"{'0': {'selected': [1], 'values': []}, '1': {'...",2021-06-23T08:59:54.002Z,78,97753
651,survey,"{'0': {'selected': [1], 'values': []}, '1': {'...",2021-06-23T08:57:39.214Z,78,18767

In [8]:
k['answers'][0]

{'0': {'selected': [2], 'values': []},
 '1': {'selected': [0], 'values': ['Telefon']},
 '2': {'selected': [2], 'values': []},
 '3': {'selected': [0], 'values': ['Telefon']},
 '4': {'selected': [0], 'values': []},
 '5': {'selected': [0], 'values': ['Telefon ']},
 '6': {'selected': [0], 'values': []},
 '7': {'selected': [0], 'values': ['Telefon']},
 '8': {'selected': [0], 'values': []},
 '9': {'selected': [0], 'values': ['Telefon']}}

In [9]:
df = pd.DataFrame()

In [10]:
for i in range(len(k)):
    row=pd.DataFrame.from_dict(k['answers'][i])
    row = row.drop(row.index[[0]])
    df = df.append(row, ignore_index=True)

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,[],[Telefon],[],[Telefon],[],[Telefon ],[],[Telefon],[],[Telefon],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],[Media Markt],[],[Trendyol],[],[Yok],[],[Yok],[],[Ankara],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],[Diğer isaretlemedim],[],[Diğer isaretlemedim],[],[Diğer cevaplamadim],[],[Diğer cevaplamadim],[],[Diğer cevaplamadim],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],[Yok],[],[Yok],[],[Yok],[],[Yok],[],[Yok],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],[Diger],[],[Diger],[],[Diger],[],[Diger],[],[Diger],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,[],[],[],[],[],[],[],[Gıda],[],[.],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
648,[],[Teknosa],[],[N11],[],[Muhatap bulmak],[],[M1],[],[Hat alma],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,[],[],[],[Vatan],[],"[,]",[],"[,]",[],"[,]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,[],[Medya market],[],[Medya market],[],[Aliskanlik],[],[Kule site],[],[Kule site],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,[],[Yok],[],[Yok],[],[Yok],[],[Yok],[],[Yok],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 44 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       652 non-null    object
 1   1       652 non-null    object
 2   2       652 non-null    object
 3   3       652 non-null    object
 4   4       652 non-null    object
 5   5       652 non-null    object
 6   6       652 non-null    object
 7   7       652 non-null    object
 8   8       652 non-null    object
 9   9       649 non-null    object
 10  10      6 non-null      object
 11  11      1 non-null      object
 12  12      1 non-null      object
 13  13      1 non-null      object
 14  14      1 non-null      object
 15  15      1 non-null      object
 16  16      1 non-null      object
 17  17      1 non-null      object
 18  18      1 non-null      object
 19  19      1 non-null      object
 20  20      1 non-null      object
 21  21      1 non-null      object
 22  22      1 non-null      object
 23  23      1 non-null      object
 24  24      1 non-null      object
 25  25      1 non-null      object
 26  26      1 non-null      object
 27  27      1 non-null      object
 28  28      1 non-null      object
 29  29      1 non-null      object
 30  30      1 non-null      object
 31  31      1 non-null      object
 32  32      1 non-null      object
 33  33      1 non-null      object
 34  34      1 non-null      object
 35  35      1 non-null      object
 36  36      1 non-null      object
 37  37      1 non-null      object
 38  38      1 non-null      object
 39  39      1 non-null      object
 40  40      1 non-null      object
 41  41      1 non-null      object
 42  42      1 non-null      object
 43  43      1 non-null      object
dtypes: object(44)
memory usage: 224.2+ KB

In [13]:
df['uid'] = k['uid']
df

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,uid
0,[],[Media markt],[],[Media markt],[],[Ürünü görüp İncelemek],[],[.],[],[.],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160595
1,[],[Vatan],[],[Vatan],[],[Ürünü görmek],[],[Novaland],[],[Novaland],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84731
2,[],[Diğer],[],[Diğer],[],[Diğer],[],[Diğer],[],[Diğer],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11467
3,[],[Media market ],[],[Hayır ],[],[Hayır ],[],[Hayır],[],[Hayır ],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34409
4,[],[.],[],[.],[],[.],[],[.],[],[Başka],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160404
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,[],[],[],[],[],[],[],[Gıda],[],[.],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92541
640,[],[Teknosa],[],[N11],[],[Muhatap bulmak],[],[M1],[],[Hat alma],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65692
641,[],[],[],[Vatan],[],"[,]",[],"[,]",[],"[,]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65699
642,[],[Medya market],[],[Medya market],[],[Aliskanlik],[],[Kule site],[],[Kule site],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97753
643,[],[Yok],[],[Yok],[],[Yok],[],[Yok],[],[Yok],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18767

In [14]:
df = df.drop(columns = ['10','11', '12', '13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43'])
df

,0,1,2,3,4,5,6,7,8,9,uid
0,[],[Media markt],[],[Media markt],[],[Ürünü görüp İncelemek],[],[.],[],[.],160595
1,[],[Vatan],[],[Vatan],[],[Ürünü görmek],[],[Novaland],[],[Novaland],84731
2,[],[Diğer],[],[Diğer],[],[Diğer],[],[Diğer],[],[Diğer],11467
3,[],[Media market ],[],[Hayır ],[],[Hayır ],[],[Hayır],[],[Hayır ],34409
4,[],[.],[],[.],[],[.],[],[.],[],[Başka],160404
...,...,...,...,...,...,...,...,...,...,...,...
639,[],[],[],[],[],[],[],[Gıda],[],[.],92541
640,[],[Teknosa],[],[N11],[],[Muhatap bulmak],[],[M1],[],[Hat alma],65692
641,[],[],[],[Vatan],[],"[,]",[],"[,]",[],"[,]",65699
642,[],[Medya market],[],[Medya market],[],[Aliskanlik],[],[Kule site],[],[Kule site],97753
643,[],[Yok],[],[Yok],[],[Yok],[],[Yok],[],[Yok],18767

In [15]:
df_sel = pd.DataFrame()

In [16]:
for i in range(len(k)):
    row=pd.DataFrame.from_dict(k['answers'][i])
    row = row.drop(row.index[[1]])
    df_sel = df_sel.append(row, ignore_index=True)

In [17]:
df_sel

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,[3],[0],[1],[0],[0],[0],[2],[0],[2],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[0],[0],[0],[0],[0],[0],[3],[0],[3],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[2],[0],[2],[0],[1],[0],[1],[0],[2],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[1],[0],[1],[0],[4],[0],[3],[0],[2],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[1],[0],[2],[0],[0],[0],[1],[0],[5],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,[2],[2],[2],[3],[4],[2],[2],[0],[1],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,[1],[0],[3],[0],[3],[0],[1],[0],[1],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,[2],[5],[2],[0],[0],[0],[0],[0],[1],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,[1],[0],[1],[0],[2],[0],[1],[0],[1],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643,[1],[0],[0],[0],[0],[0],[1],[0],[0],[0],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_sel = df_sel.drop(columns = ['10','11', '12', '13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43'])
df_sel

       0    1    2    3    4    5    6    7    8    9
0    [3]  [0]  [1]  [0]  [0]  [0]  [2]  [0]  [2]  [0]
1    [0]  [0]  [0]  [0]  [0]  [0]  [3]  [0]  [3]  [0]
2    [2]  [0]  [2]  [0]  [1]  [0]  [1]  [0]  [2]  [0]
3    [1]  [0]  [1]  [0]  [4]  [0]  [3]  [0]  [2]  [0]
4    [1]  [0]  [2]  [0]  [0]  [0]  [1]  [0]  [5]  [0]
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
639  [2]  [2]  [2]  [3]  [4]  [2]  [2]  [0]  [1]  [0]
640  [1]  [0]  [3]  [0]  [3]  [0]  [1]  [0]  [1]  [0]
641  [2]  [5]  [2]  [0]  [0]  [0]  [0]  [0]  [1]  [0]
642  [1]  [0]  [1]  [0]  [2]  [0]  [1]  [0]  [1]  [0]
643  [1]  [0]  [0]  [0]  [0]  [0]  [1]  [0]  [0]  [0]

[644 rows x 10 columns]

In [19]:
df['0'] = df_sel['0']
df['2'] = df_sel['2']
df['4'] = df_sel['4']
df['6'] = df_sel['6']
df['8'] = df_sel['8']

df

,0,1,2,3,4,5,6,7,8,9,uid
0,[3],[Media markt],[1],[Media markt],[0],[Ürünü görüp İncelemek],[2],[.],[2],[.],160595
1,[0],[Vatan],[0],[Vatan],[0],[Ürünü görmek],[3],[Novaland],[3],[Novaland],84731
2,[2],[Diğer],[2],[Diğer],[1],[Diğer],[1],[Diğer],[2],[Diğer],11467
3,[1],[Media market ],[1],[Hayır ],[4],[Hayır ],[3],[Hayır],[2],[Hayır ],34409
4,[1],[.],[2],[.],[0],[.],[1],[.],[5],[Başka],160404
...,...,...,...,...,...,...,...,...,...,...,...
639,[2],[],[2],[],[4],[],[2],[Gıda],[1],[.],92541
640,[1],[Teknosa],[3],[N11],[3],[Muhatap bulmak],[1],[M1],[1],[Hat alma],65692
641,[2],[],[2],[Vatan],[0],"[,]",[0],"[,]",[1],"[,]",65699
642,[1],[Medya market],[1],[Medya market],[2],[Aliskanlik],[1],[Kule site],[1],[Kule site],97753
643,[1],[Yok],[0],[Yok],[0],[Yok],[1],[Yok],[0],[Yok],18767

In [20]:
df = df.set_index('uid')
df = df.loc[~df.index.duplicated(), :]
df

,0,1,2,3,4,5,6,7,8,9
uid,,,,,,,,,,
160595,[3],[Media markt],[1],[Media markt],[0],[Ürünü görüp İncelemek],[2],[.],[2],[.]
84731,[0],[Vatan],[0],[Vatan],[0],[Ürünü görmek],[3],[Novaland],[3],[Novaland]
11467,[2],[Diğer],[2],[Diğer],[1],[Diğer],[1],[Diğer],[2],[Diğer]
34409,[1],[Media market ],[1],[Hayır ],[4],[Hayır ],[3],[Hayır],[2],[Hayır ]
160404,[1],[.],[2],[.],[0],[.],[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...
92541,[2],[],[2],[],[4],[],[2],[Gıda],[1],[.]
65692,[1],[Teknosa],[3],[N11],[3],[Muhatap bulmak],[1],[M1],[1],[Hat alma]
65699,[2],[],[2],[Vatan],[0],"[,]",[0],"[,]",[1],"[,]"
97753,[1],[Medya market],[1],[Medya market],[2],[Aliskanlik],[1],[Kule site],[1],[Kule site]
18767,[1],[Yok],[0],[Yok],[0],[Yok],[1],[Yok],[0],[Yok]

In [21]:
df=df.reset_index()
df

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,[3],[Media markt],[1],[Media markt],[0],[Ürünü görüp İncelemek],[2],[.],[2],[.]
1,84731,[0],[Vatan],[0],[Vatan],[0],[Ürünü görmek],[3],[Novaland],[3],[Novaland]
2,11467,[2],[Diğer],[2],[Diğer],[1],[Diğer],[1],[Diğer],[2],[Diğer]
3,34409,[1],[Media market ],[1],[Hayır ],[4],[Hayır ],[3],[Hayır],[2],[Hayır ]
4,160404,[1],[.],[2],[.],[0],[.],[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,[2],[],[2],[],[4],[],[2],[Gıda],[1],[.]
640,65692,[1],[Teknosa],[3],[N11],[3],[Muhatap bulmak],[1],[M1],[1],[Hat alma]
641,65699,[2],[],[2],[Vatan],[0],"[,]",[0],"[,]",[1],"[,]"
642,97753,[1],[Medya market],[1],[Medya market],[2],[Aliskanlik],[1],[Kule site],[1],[Kule site]
643,18767,[1],[Yok],[0],[Yok],[0],[Yok],[1],[Yok],[0],[Yok]

In [22]:
for i in range(len(df)):
    if type(df['0'][i]) == list:
        if len(df['0'][i]) == 1:
            if df['0'][i][0] == 0:
                df['0'][i] = 'Vatan'
            elif df['0'][i][0] == 1:
                df['0'][i] = 'Media Markt'
            elif df['0'][i][0] == 2:
                df['0'][i] = 'Teknosa'
            elif df['0'][i][0] == 3:
                df['0'][i] = 'Diğer'
            else:
                df['0'][i] = 'Null'
        else:
            df['0'][i] = 'Null'
    else:
        df['0'][i] = 'Null'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,[Media markt],[1],[Media markt],[0],[Ürünü görüp İncelemek],[2],[.],[2],[.]
1,84731,Vatan,[Vatan],[0],[Vatan],[0],[Ürünü görmek],[3],[Novaland],[3],[Novaland]
2,11467,Teknosa,[Diğer],[2],[Diğer],[1],[Diğer],[1],[Diğer],[2],[Diğer]
3,34409,Media Markt,[Media market ],[1],[Hayır ],[4],[Hayır ],[3],[Hayır],[2],[Hayır ]
4,160404,Media Markt,[.],[2],[.],[0],[.],[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,[],[2],[],[4],[],[2],[Gıda],[1],[.]
640,65692,Media Markt,[Teknosa],[3],[N11],[3],[Muhatap bulmak],[1],[M1],[1],[Hat alma]
641,65699,Teknosa,[],[2],[Vatan],[0],"[,]",[0],"[,]",[1],"[,]"
642,97753,Media Markt,[Medya market],[1],[Medya market],[2],[Aliskanlik],[1],[Kule site],[1],[Kule site]
643,18767,Media Markt,[Yok],[0],[Yok],[0],[Yok],[1],[Yok],[0],[Yok]

In [23]:
for i in range(len(df)):
    if len(df['1'][i]) == 1:
        df['1'][i] = df['1'][i][0]
    #elif df['1'][i][0] == '.':
        #df['1'][i] = 'Not answered'        
    else:
        df['1'][i] = 'No Store'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,[1],[Media markt],[0],[Ürünü görüp İncelemek],[2],[.],[2],[.]
1,84731,Vatan,Vatan,[0],[Vatan],[0],[Ürünü görmek],[3],[Novaland],[3],[Novaland]
2,11467,Teknosa,Diğer,[2],[Diğer],[1],[Diğer],[1],[Diğer],[2],[Diğer]
3,34409,Media Markt,Media market,[1],[Hayır ],[4],[Hayır ],[3],[Hayır],[2],[Hayır ]
4,160404,Media Markt,.,[2],[.],[0],[.],[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,[2],[],[4],[],[2],[Gıda],[1],[.]
640,65692,Media Markt,Teknosa,[3],[N11],[3],[Muhatap bulmak],[1],[M1],[1],[Hat alma]
641,65699,Teknosa,No Store,[2],[Vatan],[0],"[,]",[0],"[,]",[1],"[,]"
642,97753,Media Markt,Medya market,[1],[Medya market],[2],[Aliskanlik],[1],[Kule site],[1],[Kule site]
643,18767,Media Markt,Yok,[0],[Yok],[0],[Yok],[1],[Yok],[0],[Yok]

In [24]:
for i in range(len(df)):
    if type(df['2'][i]) == list:
        if len(df['2'][i]) == 1:
            if df['2'][i][0] == 0:
                df['2'][i] = 'Vatan'
            elif df['2'][i][0] == 1:
                df['2'][i] = 'Media Markt'
            elif df['2'][i][0] == 2:
                df['2'][i] = 'Teknosa'
            elif df['2'][i][0] == 3:
                df['2'][i] = 'İnternet Pazar Yerleri'
            elif df['2'][i][0] == 4:
                df['2'][i] = 'Diğer'
            else:
                df['2'][i] = 'Null'
        else:
            df['2'][i] = 'Null'
    else:
        df['2'][i] = 'Null'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,[Media markt],[0],[Ürünü görüp İncelemek],[2],[.],[2],[.]
1,84731,Vatan,Vatan,Vatan,[Vatan],[0],[Ürünü görmek],[3],[Novaland],[3],[Novaland]
2,11467,Teknosa,Diğer,Teknosa,[Diğer],[1],[Diğer],[1],[Diğer],[2],[Diğer]
3,34409,Media Markt,Media market,Media Markt,[Hayır ],[4],[Hayır ],[3],[Hayır],[2],[Hayır ]
4,160404,Media Markt,.,Teknosa,[.],[0],[.],[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,[],[4],[],[2],[Gıda],[1],[.]
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,[N11],[3],[Muhatap bulmak],[1],[M1],[1],[Hat alma]
641,65699,Teknosa,No Store,Teknosa,[Vatan],[0],"[,]",[0],"[,]",[1],"[,]"
642,97753,Media Markt,Medya market,Media Markt,[Medya market],[2],[Aliskanlik],[1],[Kule site],[1],[Kule site]
643,18767,Media Markt,Yok,Vatan,[Yok],[0],[Yok],[1],[Yok],[0],[Yok]

In [25]:
for i in range(len(df)):
    if len(df['3'][i]) == 1:
        df['3'][i] = df['3'][i][0]        
    else:
        df['3'][i] = 'No visits'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,[0],[Ürünü görüp İncelemek],[2],[.],[2],[.]
1,84731,Vatan,Vatan,Vatan,Vatan,[0],[Ürünü görmek],[3],[Novaland],[3],[Novaland]
2,11467,Teknosa,Diğer,Teknosa,Diğer,[1],[Diğer],[1],[Diğer],[2],[Diğer]
3,34409,Media Markt,Media market,Media Markt,Hayır,[4],[Hayır ],[3],[Hayır],[2],[Hayır ]
4,160404,Media Markt,.,Teknosa,.,[0],[.],[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,[4],[],[2],[Gıda],[1],[.]
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,[3],[Muhatap bulmak],[1],[M1],[1],[Hat alma]
641,65699,Teknosa,No Store,Teknosa,Vatan,[0],"[,]",[0],"[,]",[1],"[,]"
642,97753,Media Markt,Medya market,Media Markt,Medya market,[2],[Aliskanlik],[1],[Kule site],[1],[Kule site]
643,18767,Media Markt,Yok,Vatan,Yok,[0],[Yok],[1],[Yok],[0],[Yok]

In [26]:
for i in range(len(df)):
    if type(df['4'][i]) == list:
        if len(df['4'][i]) == 1:
            if df['4'][i][0] == 0:
                df['4'][i] = 'Ürünü görmek'
            elif df['4'][i][0] == 1:
                df['4'][i] = 'Satış temsilcisinden hızlı bilgiye erişebilmek'
            elif df['4'][i][0] == 2:
                df['4'][i] = 'Alışkanlık'
            elif df['4'][i][0] == 3:
                df['4'][i] = 'Satın alma davranışı sonrasında muhatap kişiye kolay ulaşım'
            elif df['4'][i][0] == 4:
                df['4'][i] = 'Güvenilir olması'
            elif df['4'][i][0] == 5:
                df['4'][i] = 'Aktüel'
            elif df['4'][i][0] == 6:
                df['4'][i] = 'Diğer'
            else:
                df['4'][i] = 'Null'
        else:
            df['4'][i] = 'Null'
    else:
        df['4'][i] = 'Null'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,Ürünü görmek,[Ürünü görüp İncelemek],[2],[.],[2],[.]
1,84731,Vatan,Vatan,Vatan,Vatan,Ürünü görmek,[Ürünü görmek],[3],[Novaland],[3],[Novaland]
2,11467,Teknosa,Diğer,Teknosa,Diğer,Satış temsilcisinden hızlı bilgiye erişebilmek,[Diğer],[1],[Diğer],[2],[Diğer]
3,34409,Media Markt,Media market,Media Markt,Hayır,Güvenilir olması,[Hayır ],[3],[Hayır],[2],[Hayır ]
4,160404,Media Markt,.,Teknosa,.,Ürünü görmek,[.],[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,Güvenilir olması,[],[2],[Gıda],[1],[.]
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,Satın alma davranışı sonrasında muhatap kişiye...,[Muhatap bulmak],[1],[M1],[1],[Hat alma]
641,65699,Teknosa,No Store,Teknosa,Vatan,Ürünü görmek,"[,]",[0],"[,]",[1],"[,]"
642,97753,Media Markt,Medya market,Media Markt,Medya market,Alışkanlık,[Aliskanlik],[1],[Kule site],[1],[Kule site]
643,18767,Media Markt,Yok,Vatan,Yok,Ürünü görmek,[Yok],[1],[Yok],[0],[Yok]

In [27]:
for i in range(len(df)):
    if len(df['5'][i]) == 1:
        df['5'][i] = df['5'][i][0]        
    else:
        df['5'][i] = 'Neither'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,Ürünü görmek,Ürünü görüp İncelemek,[2],[.],[2],[.]
1,84731,Vatan,Vatan,Vatan,Vatan,Ürünü görmek,Ürünü görmek,[3],[Novaland],[3],[Novaland]
2,11467,Teknosa,Diğer,Teknosa,Diğer,Satış temsilcisinden hızlı bilgiye erişebilmek,Diğer,[1],[Diğer],[2],[Diğer]
3,34409,Media Markt,Media market,Media Markt,Hayır,Güvenilir olması,Hayır,[3],[Hayır],[2],[Hayır ]
4,160404,Media Markt,.,Teknosa,.,Ürünü görmek,.,[1],[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,Güvenilir olması,Neither,[2],[Gıda],[1],[.]
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,Satın alma davranışı sonrasında muhatap kişiye...,Muhatap bulmak,[1],[M1],[1],[Hat alma]
641,65699,Teknosa,No Store,Teknosa,Vatan,Ürünü görmek,",",[0],"[,]",[1],"[,]"
642,97753,Media Markt,Medya market,Media Markt,Medya market,Alışkanlık,Aliskanlik,[1],[Kule site],[1],[Kule site]
643,18767,Media Markt,Yok,Vatan,Yok,Ürünü görmek,Yok,[1],[Yok],[0],[Yok]

In [28]:
for i in range(len(df)):
    if type(df['6'][i]) == list:
        if len(df['6'][i]) == 1:
            if df['6'][i][0] == 0:
                df['6'][i] = 'Kentplaza AVM'
            elif df['6'][i][0] == 1:
                df['6'][i] = 'Kule Site'
            elif df['6'][i][0] == 2:
                df['6'][i] = 'M1'
            elif df['6'][i][0] == 3:
                df['6'][i] = 'Novaland'
            elif df['6'][i][0] == 4:
                df['6'][i] = 'Selçuker Center'
            elif df['6'][i][0] == 5:
                df['6'][i] = 'Diğer'
            else:
                df['6'][i] = 'Null'
        else:
            df['6'][i] = 'Null'
    else:
        df['6'][i] = 'Null'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,Ürünü görmek,Ürünü görüp İncelemek,M1,[.],[2],[.]
1,84731,Vatan,Vatan,Vatan,Vatan,Ürünü görmek,Ürünü görmek,Novaland,[Novaland],[3],[Novaland]
2,11467,Teknosa,Diğer,Teknosa,Diğer,Satış temsilcisinden hızlı bilgiye erişebilmek,Diğer,Kule Site,[Diğer],[2],[Diğer]
3,34409,Media Markt,Media market,Media Markt,Hayır,Güvenilir olması,Hayır,Novaland,[Hayır],[2],[Hayır ]
4,160404,Media Markt,.,Teknosa,.,Ürünü görmek,.,Kule Site,[.],[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,Güvenilir olması,Neither,M1,[Gıda],[1],[.]
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,Satın alma davranışı sonrasında muhatap kişiye...,Muhatap bulmak,Kule Site,[M1],[1],[Hat alma]
641,65699,Teknosa,No Store,Teknosa,Vatan,Ürünü görmek,",",Kentplaza AVM,"[,]",[1],"[,]"
642,97753,Media Markt,Medya market,Media Markt,Medya market,Alışkanlık,Aliskanlik,Kule Site,[Kule site],[1],[Kule site]
643,18767,Media Markt,Yok,Vatan,Yok,Ürünü görmek,Yok,Kule Site,[Yok],[0],[Yok]

In [29]:
for i in range(len(df)):
    if len(df['7'][i]) == 1:
        df['7'][i] = df['7'][i][0]        
    else:
        df['7'][i] = 'No mall'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,Ürünü görmek,Ürünü görüp İncelemek,M1,.,[2],[.]
1,84731,Vatan,Vatan,Vatan,Vatan,Ürünü görmek,Ürünü görmek,Novaland,Novaland,[3],[Novaland]
2,11467,Teknosa,Diğer,Teknosa,Diğer,Satış temsilcisinden hızlı bilgiye erişebilmek,Diğer,Kule Site,Diğer,[2],[Diğer]
3,34409,Media Markt,Media market,Media Markt,Hayır,Güvenilir olması,Hayır,Novaland,Hayır,[2],[Hayır ]
4,160404,Media Markt,.,Teknosa,.,Ürünü görmek,.,Kule Site,.,[5],[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,Güvenilir olması,Neither,M1,Gıda,[1],[.]
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,Satın alma davranışı sonrasında muhatap kişiye...,Muhatap bulmak,Kule Site,M1,[1],[Hat alma]
641,65699,Teknosa,No Store,Teknosa,Vatan,Ürünü görmek,",",Kentplaza AVM,",",[1],"[,]"
642,97753,Media Markt,Medya market,Media Markt,Medya market,Alışkanlık,Aliskanlik,Kule Site,Kule site,[1],[Kule site]
643,18767,Media Markt,Yok,Vatan,Yok,Ürünü görmek,Yok,Kule Site,Yok,[0],[Yok]

In [30]:
for i in range(len(df)):
    if type(df['8'][i]) == list:
        if len(df['8'][i]) == 1:
            if df['8'][i][0] == 0:
                df['8'][i] = 'Kentplaza AVM'
            elif df['8'][i][0] == 1:
                df['8'][i] = 'Kule Site'
            elif df['8'][i][0] == 2:
                df['8'][i] = 'M1'
            elif df['8'][i][0] == 3:
                df['8'][i] = 'Novaland'
            elif df['8'][i][0] == 4:
                df['8'][i] = 'Selçuker Center'
            elif df['8'][i][0] == 5:
                df['8'][i] = 'Diğer'
            else:
                df['8'][i] = 'Null'
        else:
            df['8'][i] = 'Null'
    else:
        df['8'][i] = 'Null'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,Ürünü görmek,Ürünü görüp İncelemek,M1,.,M1,[.]
1,84731,Vatan,Vatan,Vatan,Vatan,Ürünü görmek,Ürünü görmek,Novaland,Novaland,Novaland,[Novaland]
2,11467,Teknosa,Diğer,Teknosa,Diğer,Satış temsilcisinden hızlı bilgiye erişebilmek,Diğer,Kule Site,Diğer,M1,[Diğer]
3,34409,Media Markt,Media market,Media Markt,Hayır,Güvenilir olması,Hayır,Novaland,Hayır,M1,[Hayır ]
4,160404,Media Markt,.,Teknosa,.,Ürünü görmek,.,Kule Site,.,Diğer,[Başka]
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,Güvenilir olması,Neither,M1,Gıda,Kule Site,[.]
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,Satın alma davranışı sonrasında muhatap kişiye...,Muhatap bulmak,Kule Site,M1,Kule Site,[Hat alma]
641,65699,Teknosa,No Store,Teknosa,Vatan,Ürünü görmek,",",Kentplaza AVM,",",Kule Site,"[,]"
642,97753,Media Markt,Medya market,Media Markt,Medya market,Alışkanlık,Aliskanlik,Kule Site,Kule site,Kule Site,[Kule site]
643,18767,Media Markt,Yok,Vatan,Yok,Ürünü görmek,Yok,Kule Site,Yok,Kentplaza AVM,[Yok]

In [31]:
for i in range(len(df)):
    if type(df['9'][i]) == list:
        if len(df['9'][i]) == 1:
            df['9'][i] = df['9'][i][0]
        else:
            df['9'][i] = 'No expenditure'
    else:
        df['9'][i] = 'No expenditure'
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,Ürünü görmek,Ürünü görüp İncelemek,M1,.,M1,.
1,84731,Vatan,Vatan,Vatan,Vatan,Ürünü görmek,Ürünü görmek,Novaland,Novaland,Novaland,Novaland
2,11467,Teknosa,Diğer,Teknosa,Diğer,Satış temsilcisinden hızlı bilgiye erişebilmek,Diğer,Kule Site,Diğer,M1,Diğer
3,34409,Media Markt,Media market,Media Markt,Hayır,Güvenilir olması,Hayır,Novaland,Hayır,M1,Hayır
4,160404,Media Markt,.,Teknosa,.,Ürünü görmek,.,Kule Site,.,Diğer,Başka
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,Güvenilir olması,Neither,M1,Gıda,Kule Site,.
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,Satın alma davranışı sonrasında muhatap kişiye...,Muhatap bulmak,Kule Site,M1,Kule Site,Hat alma
641,65699,Teknosa,No Store,Teknosa,Vatan,Ürünü görmek,",",Kentplaza AVM,",",Kule Site,","
642,97753,Media Markt,Medya market,Media Markt,Medya market,Alışkanlık,Aliskanlik,Kule Site,Kule site,Kule Site,Kule site
643,18767,Media Markt,Yok,Vatan,Yok,Ürünü görmek,Yok,Kule Site,Yok,Kentplaza AVM,Yok

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 644 entries, 0 to 643
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uid     644 non-null    int64
 1   0       644 non-null    object
 2   1       644 non-null    object
 3   2       644 non-null    object
 4   3       644 non-null    object
 5   4       644 non-null    object
 6   5       644 non-null    object
 7   6       644 non-null    object
 8   7       644 non-null    object
 9   8       644 non-null    object
 10  9       644 non-null    object
dtypes: int64(1), object(10)
memory usage: 55.5+ KB

In [33]:
df

,uid,0,1,2,3,4,5,6,7,8,9
0,160595,Diğer,Media markt,Media Markt,Media markt,Ürünü görmek,Ürünü görüp İncelemek,M1,.,M1,.
1,84731,Vatan,Vatan,Vatan,Vatan,Ürünü görmek,Ürünü görmek,Novaland,Novaland,Novaland,Novaland
2,11467,Teknosa,Diğer,Teknosa,Diğer,Satış temsilcisinden hızlı bilgiye erişebilmek,Diğer,Kule Site,Diğer,M1,Diğer
3,34409,Media Markt,Media market,Media Markt,Hayır,Güvenilir olması,Hayır,Novaland,Hayır,M1,Hayır
4,160404,Media Markt,.,Teknosa,.,Ürünü görmek,.,Kule Site,.,Diğer,Başka
...,...,...,...,...,...,...,...,...,...,...,...
639,92541,Teknosa,No Store,Teknosa,No visits,Güvenilir olması,Neither,M1,Gıda,Kule Site,.
640,65692,Media Markt,Teknosa,İnternet Pazar Yerleri,N11,Satın alma davranışı sonrasında muhatap kişiye...,Muhatap bulmak,Kule Site,M1,Kule Site,Hat alma
641,65699,Teknosa,No Store,Teknosa,Vatan,Ürünü görmek,",",Kentplaza AVM,",",Kule Site,","
642,97753,Media Markt,Medya market,Media Markt,Medya market,Alışkanlık,Aliskanlik,Kule Site,Kule site,Kule Site,Kule site
643,18767,Media Markt,Yok,Vatan,Yok,Ürünü görmek,Yok,Kule Site,Yok,Kentplaza AVM,Yok

In [36]:
url2="https://endapi.truefeedback.io/dataplatform/survey/"
s=requests.get(url2,headers={"auth": token}).content
k=pd.read_json(s)
k

,id,title,questionCount,description,image,totalTfb,participantLimit,answerable,answerCount
0,79,{'tr': 'Kentplaza Carrefour Anketi'},8,{'tr': 'Kentplaza Carrefour Anketi'},randCollection/back_23.png,50000,1000.0,True,676
1,78,{'tr': 'Konya Elektronik Market Anketi'},10,{'tr': 'Konya Elektronik Market Anketi'},randCollection/back_24.png,50000,1000.0,True,645
2,1,"{'en': 'TFB Welcome Survey', 'tr': 'TFB Hoşgel...",11,"{'en': 'Welcome', 'tr': 'Hoşgeldin'}",randCollection/back_1.png,500,NaN,True,35216
3,95,"{'en': 'UEFA Euro 2020 | England vs Denmark', ...",2,"{'en': 'UEFA Euro 2020 | England vs Denmark', ...",image.png,25000,5000.0,False,2657
4,94,"{'en': 'UEFA Euro 2020 | Spain vs Italy', 'tr'...",2,"{'en': 'UEFA Euro 2020 | Spain vs Italy', 'tr'...",image.png,25000,5000.0,False,2667